hpge_ic_nplus_surface:
  command: >-
    revertex hpge-surf-pos --detectors V* --surface-type nplus --gdml
    {GDML_FILE} --out-file {OUTPUT_FILE} --n-events {N_EVENTS}

hpge_bege_nplus_surface:
  command: >-
    revertex hpge-surf-pos --detectors B* --surface-type nplus --gdml
    {GDML_FILE} --out-file {OUTPUT_FILE} --n-events {N_EVENTS}

hpge_ppc_nplus_surface:
  command: >-
    revertex hpge-surf-pos --detectors P* --surface-type nplus --gdml
    {GDML_FILE} --out-file {OUTPUT_FILE} --n-events {N_EVENTS}

hpge_coax_nplus_surface:
  command: >-
    revertex hpge-surf-pos --detectors P* --surface-type nplus --gdml
    {GDML_FILE} --out-file {OUTPUT_FILE} --n-events {N_EVENTS}

hpge_ic_pplus_surface:
  command: >-
    revertex hpge-surf-pos --detectors V* --surface-type pplus --gdml
    {GDML_FILE} --out-file {OUTPUT_FILE} --n-events {N_EVENTS}

hpge_bege_pplus_surface:
  command: >-
    revertex hpge-surf-pos --detectors B* --surface-type pplus --gdml
    {GDML_FILE} --out-file {OUTPUT_FILE} --n-events {N_EVENTS}

hpge_ppc_pplus_surface:
  command: >-
    revertex hpge-surf-pos --detectors P* --surface-type pplus --gdml
    {GDML_FILE} --out-file {OUTPUT_FILE} --n-events {N_EVENTS}

hpge_coax_pplus_surface:
  command: >-
    revertex hpge-surf-pos --detectors P* --surface-type pplus --gdml
    {GDML_FILE} --out-file {OUTPUT_FILE} --n-events {N_EVENTS}
