hpge_nplus_surface_ic:
  command: >-
    revertex hpge-surf-pos --detectors V* --surface-type nplus --gdml
    {GDML_FILE} --out-file {OUTPUT_FILE} --n-events {N_EVENTS}

hpge_nplus_surface_bege:
  command: >-
    revertex hpge-surf-pos --detectors B* --surface-type nplus --gdml
    {GDML_FILE} --out-file {OUTPUT_FILE} --n-events {N_EVENTS}

hpge_nplus_surface_ppc:
  command: >-
    revertex hpge-surf-pos --detectors P* --surface-type nplus --gdml
    {GDML_FILE} --out-file {OUTPUT_FILE} --n-events {N_EVENTS}

hpge_nplus_surface_coax:
  command: >-
    revertex hpge-surf-pos --detectors P* --surface-type nplus --gdml
    {GDML_FILE} --out-file {OUTPUT_FILE} --n-events {N_EVENTS}
