# p16-ssc simulations
# -------------------

# HACK: there are no runtime differences between all the p16-ssc runs.
# therefore, we just use the first here

sis1_z8230_slot2_Bi212_to_Pb208:
  runlist:
    - l200-p16-r008-ssc

sis1_z8430_slot2_Bi212_to_Pb208:
  runlist:
    - l200-p16-r008-ssc

sis1_z8630_slot2_Bi212_to_Pb208:
  runlist:
    - l200-p16-r008-ssc

sis1_z8830_slot2_Bi212_to_Pb208:
  runlist:
    - l200-p16-r008-ssc

sis2_z8300_slot2_Bi212_to_Pb208:
  runlist:
    - l200-p16-r008-ssc

sis2_z8700_slot2_Bi212_to_Pb208:
  runlist:
    - l200-p16-r008-ssc

sis3_z8450_slot2_Bi212_to_Pb208:
  runlist:
    - l200-p16-r008-ssc

sis3_z8650_slot2_Bi212_to_Pb208:
  runlist:
    - l200-p16-r008-ssc

sis4_z8230_slot2_Bi212_to_Pb208:
  runlist:
    - l200-p16-r008-ssc

sis4_z8430_slot2_Bi212_to_Pb208:
  runlist:
    - l200-p16-r008-ssc

sis4_z8630_slot2_Bi212_to_Pb208:
  runlist:
    - l200-p16-r008-ssc

# p16-rdc simulations
# -------------------

sis1_z8640_slot3_Pb214_to_Po214:
  runlist:
    - l200-p16-r019-rdc

sis1_z8580_slot2_Pb214_to_Po214:
  runlist:
    - l200-p16-r019-rdc
